# Generated by Django 5.2.4 on 2026-03-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ticker_alter_tradetransaction_ticker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12),
        ),
    ]
